import { PlaceholderPage } from "@/components/PlaceholderPage";

export default function TermsOfServicePage() {
  return (
    <PlaceholderPage title="Terms of Service">
      <div className="space-y-6">
        <section>
          <h2 className="text-xl font-semibold mb-2">1. Acceptance of Terms</h2>
          <p>
            By accessing or using Break the Ice, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the application.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">2. Use License</h2>
          <p>
            You are free to use the questions and content generated by Break the Ice for any purpose, including both personal and commercial use.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">3. User Contributions & Ownership</h2>
          <p>
            You retain full ownership of any questions or content you submit to the application. By submitting content, you grant Break the Ice a non-exclusive, royalty-free, worldwide license to use, display, and distribute that content to other users within the application's framework.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">4. AI-Generated Content Disclaimer</h2>
          <p>
            Some content within Break the Ice is generated by artificial intelligence. While we strive for quality, we do not guarantee the accuracy, appropriateness, or uniqueness of AI-generated text. You use AI-generated content at your own risk.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">5. Prohibited Conduct</h2>
          <p>
            To maintain a positive environment, you agree not to:
          </p>
          <ul className="list-disc ml-6 mt-2 space-y-1">
            <li>Submit content that is illegal, harmful, or promotes hate speech.</li>
            <li>Attempt to interfere with the application's security or performance.</li>
            <li>Use the application to harass or spam other users.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">6. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your access to the application at our sole discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users or our business interests.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">7. Changes to Terms</h2>
          <p>
            We may update these Terms from time to time. Your continued use of the application after changes are posted constitutes your acceptance of the new Terms.
          </p>
        </section>
      </div>
    </PlaceholderPage>
  );
}
